POST http://localhost:3333/cadastro
Content-Type: application/json

{
    "login": "carlos",
    "password": "289412nf23123"
}


###

GET https://backend-guildmaster.onrender.com/usuarios?search=joao


###

PUT http://localhost:3333/usuarios/c4bfc20a-1da7-4b60-ae10-484cfef7047a
Content-Type: application/json

{
    "login": "lindomar",
    "password": "289412nf232333333"
}

###

DELETE http://localhost:3333/usuarios/c4bfc20a-1da7-4b60-ae10-484cfef7047a